# Configure the database used when in the development environment
development:
  adapter: postgresql
  encoding: unicode
  database: floof_walks_development
  pool: 5
  username:
  password:

# Configure the database used when in the production environment
production:
  adapter: postgresql
  encoding: unicode
  database: floof_walks__production
  pool: 5
  username:
  password:
